- samples/botframework-webchat-control/src/components/WebChat/WebChat.tsx
Currently VoiceVideoCalling is loaded dynamically based on:
https://github.com/microsoft/omnichannel-chat-sdk/blob/3b3e3ff4f8a3afd1677be4da94b4382277ffaf8e/samples/botframework-webchat-control/src/components/WebChat/WebChat.tsx#L56
The close button will try to close this session first, which fails if the `VoiceVideoCallingSDK` is not loaded. Due to this, the following calls to clean the session state / local storage will fail as well.
> [botframework-webchat-control] Add optional check to VoiceVideoCalling

- samples/botframework-webchat-control/src/components/WebChat/WebChat.tsx
> Fix "Cannot read property 'getVoiceVideoCalling' of undefined" on botframework-webchat-control

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- src/OmnichannelChatSDK.ts
Session Init failures can be caught as follow:
```js
try {
await chatSDK.startChat();
} catch (error) {
console.log(`Unable to start chat: ${error.message}`);
}
```
> Bubble up session init failures

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/ChatSDKExceptionDetails.ts
- src/core/OmnichannelErrorCodes.ts
Usage 
```js
try {
await chatSDK.startChat();
} catch (error) {
if (error.message === 'WidgetUseOutsideOperatingHour') {
// Handles widget outside of operating hours
}
}
```
> Raise start chat ooh failure

- CHANGELOG.md
- README.md
- __tests__/OmnichannelChatSDK.node.spec.ts
- __tests__/OmnichannelChatSDK.web.spec.ts
- src/OmnichannelChatSDK.ts
We can capture `ChatSDK.getVoiceVideoCalling()` errors as follow:
```js
try {
const VoiceVideoCalling = await chatSDK.getVoiceVideoCalling();
} catch (e) {
if (e.message === 'FeatureDisabled') {
// Voice Video Calling feature is disabled on admin side
}
}
// VoiceVideoCalling is undefined at this point
if (!VoiceVideoCalling) {
// Handle scenario if VoiceVideoCalling is undefined
}
```
> Calling error handling

- CHANGELOG.md
- __tests__/external/ACSAdapter/AMSFileManager.spec.ts
- src/external/ACSAdapter/AMSFileManager.ts
- Adding checks to prevent methods to be called when properties with attachment are not present
> Fix ams file manager

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
- src/core/messaging/ACSClient.ts
1. Tested multiple chats without closing or refreshing the browser. Exchanged messages between the customer and agent. Works fine.
2. Tested the chat after refreshing the browser window. Exchanged messages between the customer and agent. Works fine.
> Pass ACS chat client  during adapter initialization

- CHANGELOG.md
- __tests__/external/ACSAdapter/AMSFileManager.spec.ts
- __tests__/utils/createOmnichannelMessage.spec.ts
- src/OmnichannelChatSDK.ts
- src/config/settings.ts
- src/external/ACSAdapter/AMSFileManager.ts
- src/utils/createOmnichannelMessage.ts
- Attachments longer than 7 days would be deleted due to `amsReferences` was being used instead of `amsreferences`
- Updated code to use `amsreferences` property instead of `amsReferences` & ensure backward compatibility
> Fix attachment property

- CHANGELOG.md
- __tests__/utils/createOmnichannelMessage.spec.ts
- src/external/ACSAdapter/AMSFileManager.ts
- src/utils/createOmnichannelMessage.ts
- Uptaking AMSClient required to update the dependents to pass the MIME types instead of file extensions which was not the case with ChatSDK causing attachment download failures, so this PR should address the issue
> Fix Attachment Download

- CHANGELOG.md
- __tests__/utils/createOmnichannelMessage.spec.ts
- src/utils/createOmnichannelMessage.ts
- Messages without attachment should not contain `fileMetadata` property
- We usually use check if `message.fileMetadata` is defined to validate if there's an attachment or not
> Fix messages with invalid fileMetadata property

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDK.web.spec.ts
- src/OmnichannelChatSDK.ts
- src/config/settings.ts
- src/core/ChatSDKErrors.ts
- src/core/messaging/ChatAdapterConfig.ts
- src/core/messaging/ChatAdapterOptionalParams.ts
- src/telemetry/AriaTelemetry.ts
- src/telemetry/TelemetryEvent.ts
- src/utils/chatAdapterCreators.ts
- src/utils/libraries.ts
- src/utils/urlResolvers.ts
- Allow `ChatSDK.createChatAdapter()` to return adapter for `DirectLine` protocol
- Add telemetry event for `CreateACSAdapter`
```
const chatAdapter = await chatSDK.createChatAdapter({
protocol: 'DirectLine',
DirectLine: {
options: {
token: 'token'
}
}
});
```
> Create DirectLine Adapter

- CHANGELOG.md
- __tests__/utils/sleep.spec.ts
- playwright/integrations/unauthenticated-chat.spec.ts
- playwright/integrations/utilities.spec.ts
- playwright/public/scripts/globals.js
- src/core/ChatSDKErrors.ts
- src/core/ChatSDKExceptionDetails.ts
- src/utils/WebUtils.ts
- src/utils/chatAdapterCreators.ts
- src/utils/sleep.ts
- Add additional details on `ChatSDK.createChatAdapter()` failure when script fails to load
- It should provide the following exception details: `{"response":"ScriptLoadFailure","errorObject":"Error: Resource failed to load, or can't be used."}`
- Add chat adapter script load retries for up to 3 times with exponential backoff mechanism
- Add integration tests for `ChatSDK.createChatAdapter()`
> Create Chat Adapter Error Handling & Improvements

- CHANGELOG.md
- playwright/integrations/unauthenticated-chat.spec.ts
- src/core/messaging/ACSClient.ts
- Addressing #135 
- `onTypingEvent()` is not filtering user's own typing events
> Fix on typing event

- playwright/integrations/authenticated-chat-with-typing.spec.ts
- playwright/integrations/authenticated-chat.spec.ts
- playwright/test.config.sample.yml
- playwright/utils/OmnichannelEndpoints.ts
This PR includes the following authenticated chat scenarios,
1.ChatSDK.sendTyping() should not fail.
2. ChatSDK.onTypingEvent() should not fail. 
3. ChatSDK.startChat() with liveChatContext should not perform session init & validate the live work item details & validate auth map record.
4. ChatSDK.endChat() should perform session close.
> Integrated Chat SDK tests

- playwright/integrations/authenticated-chat-with-attachments.spec.ts
- playwright/integrations/authenticated-chat-with-reconnect.spec.ts
- playwright/test.config.sample.yml
- playwright/utils/OmnichannelEndpoints.ts
This PR includes the following authentication chat scenarios,
1. ChatSDK.uploadFileAttachment() should upload attachment to the attachment service & send a message with the metadata.
2. ChatSDK.downloadFileAttachment() should download an attachment.
3. ChatSDK.getChatReconnectContext() should not return a reconnect id if theres no existing chat session.
> Chat SDK tests

- playwright/integrations/authenticated-chat-with-prechat.spec.ts
- playwright/integrations/unauthenticated-chat-with-prechat.spec.ts
- playwright/test.config.sample.yml
This PR includes the following chat scenarios,
1. ChatSDK.startChat() with preChatResponse should be part of session init payload (authenticated chat).
2. ChatSDK.getPreChatSurvey() should return the survey in JSON format.
3. ChatSDK.getPreChatSurvey() with parseToJSON set to true should return the survey as JSON format.
4. ChatSDK.getPreChatSurvey() with parseToJSON set to false should return the survey as string format.
> Integrated Chat SDK Pre chat tests

- playwright/integrations/unauthenticated-chat-with-reconnect.spec.ts
This PR includes the following scenario,
1. ChatSDK.getChatReconnectContext() with invalid reconnect id should not return any reconnect id.
> Chat SDK reconnect tests

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- playwright/integrations/unauthenticated-chat-with-transcripts.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/ChatSDKErrors.ts
- src/core/GetLiveChatTranscriptOptionalParams.ts
- src/utils/exceptionThrowers.ts
- Add ability to fetch live chat transcripts via `liveChatContext`
- It would allow users to call `chatSDK.getLiveChatTranscript({liveChatContext});` after `chatSDK.endChat()` as long as `liveChatContext` is still valid
> Get live chat transcripts with live chat context

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
[Bug 3365987](https://dev.azure.com/dynamicscrm/OneCRM/_workitems/edit/3365987): [LCW V2]: Custom context with empty or null is not excluded in V2
> Skipped empty string or null context variables

- __tests__/OmnichannelChatSDK.node.spec.ts
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDK.web.spec.ts
- package-lock.json
- src/validators/OmnichannelConfigValidator.ts
we have detected in telemetry several entries without values for OrgId, WidgetId and OrgUrl.
in chat-sdk is only validated the presence of the property, but no the presence of the value, 
in this PR I'm addressing that issue
- add validation for values of the required properties
- fix tests
- additional tests for empty string and string with blank space
> Add validation for present values in telemetry

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
- src/api/createVoiceVideoCalling.ts
- src/core/GetChatTokenOptionalParams.ts
- src/core/messaging/ACSClient.ts
- src/core/messaging/ACSClientConfig.ts
- src/utils/chatAdapterCreators.ts
- src/utils/exceptionSuppressors.ts
- src/utils/exceptionThrowers.ts
- Pass `tokenRefresher` to fetch `chatToken` when getting closer to expiry
- Reduce `chatToken` call retries to 2
- Include user display name on sending typing notification
> Token Refresher

- CHANGELOG.md
- playwright/playwright.config.ts
- src/OmnichannelChatSDK.ts
- Adding `async` to internal transcript call. Otherwise, it would only return the unfulfilled promise without the transcript response.
> Add Async to Internal Live Chat Transcript Call

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
- Fix token refresher mechanism not updating chat token on AMS Client
- AMSClient should have the new chat token updated on expiry
- Attachment uploads/downloads should work after a chat token has been refreshed
> Fix tokenRefresher mechanism with attachments

- __tests__/external/ACSAdapter/AMSFileScanner.spec.ts
- __tests__/external/ACSAdapter/createFileScanIngressMiddleware.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/messaging/ChatAdapterOptionalParams.ts
- src/external/ACSAdapter/AMSFileManager.ts
- src/external/ACSAdapter/AMSFileScanner.ts
- src/external/ACSAdapter/activityUtils.ts
- src/external/ACSAdapter/createFileScanIngressMiddleware.ts
- src/utils/WebUtils.ts
- src/utils/chatAdapterCreators.ts
- Currently, attachment files with `in progress` or `malicious` states can be downloaded
- Any attachment files not with `passed` state won't be able to be downloaded. 
- The `File.content` of the attachment in `malicious` state be will removed. 
- Attachment files with `in progress` state would be added to the file scanning, its state would be periodically verified until we get a definite state (`passed` or `malicious`), then it would be handled accordingly
```ts
const fileScan: any = {
disabled: false, // disabled by default to ensure backward compability
scanPollingInterval: 30 * 1000 // file scan polling interval (default: 7 seconds)
scanStatusRetrievalDelay: 1000 // wait time between subsequent scan status retrieval API call (default: 1 second)
};
const chatAdapter: any = await …
```
> Attachment File Scan

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- src/OmnichannelChatSDK.ts
- src/telemetry/TelemetryEvent.ts
For Auth chats with invalid reconnection id , is missing the redirection URL as part of the response 
Solution
Obtain the redirection URL when checking for connection availability, this call returns  : 
- isRecconnectable (true if session is valid)
- reconnectionId
- redirect URL
__if reconnectable is false, then there is no point in checking for oauth reconnectable chats__, so we will break the flow at this point and return the redirection URL
- refresh
- connecting to the chat using the reconnection URL
-  connecting to the chat using a reconnection URL in a different browser
- refresh with the reconnection URL defined in the browser
- try to reconnect using URL, but being redirected due to an expired token
- reconnection and redirection using URL with an expired token
- reconnection …
> Adding redirect for oauth reconnection

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
[Task 3656723](https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/3656723): investigate : : Cannot read properties of undefined (reading 'customContext'
> Fixed an issue where startChat failed due to optionalParam being null

- CHANGELOG.md
- package-lock.json
- package.json
- src/external/ACSAdapter/AMSFileManager.ts
Currently when createObject or uploadDocument requests failed, it is still treated as a success, and a message is sent to ACS. This is causing data loss, as on C2 side the attachment is marked as successfully sent while in reality it is not
ams-client PR: https://github.com/microsoft/omnichannel-amsclient/pull/36
> Added error handling for createObject and uploadDocument

- CHANGELOG.md
- src/utils/exceptionThrowers.ts
Current returned error object (changed default "Error" into "CustomChatSDKError" class)
> Add `httpResponseStatusCode` into the thrown error

- CHANGELOG.md
- __tests__/core/messaging/ACSClient.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/messaging/ACSClient.ts
- src/utils/createOmnichannelMessage.ts
**Problem:**
`chat.onNewMessage()` was not recognizing queue position message edits. Investigations traced root cause to queue position message edits coming in as `chatMessageEdited` event type, not `chatMessageReceived`.
**Solution:**
Add a `chatMessageEdited` listener to listen to those queue position message edit events. `chatMessageEdited` events contain this `editedOn` property. For this edited message, `createdOn` timestamp will be updated with `editedOn` timestamp. 
Video demo: https://microsoft-my.sharepoint.com/:v:/p/kevinlin/EZsNY7oI5QRGqlacnUVDbo8BlT8Sy2pQ5CRqq-tdTWOeSw?e=PtIX9k
> Fix queue position message edits being recognized  in chatSDK onNewMessage()

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
- Changes to retrieve config from runtime cache instead since it already exists instead of making additional HTTP call
> Reduce Config Calls on Escalation to Voice & Video

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/ChatSDKError.ts
- src/core/SetAuthTokenProviderOptionalParams.ts
- Update `ChatSDKConfig.getAuthToken` to be optional
- Throw exceptions on `ChatSDK.startChat()` if `ChatSDKConfig.getAuthToken()` fails
> Authenticated Chat Improvements

- CHANGELOG.md
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
- src/core/ChatSDKConfig.ts
- src/core/LiveChatContext.ts
- Handle lifecycle of `sessionId` to improve the security of unauth endpoints 
- Retrieving `sessionId` if exits after `getchattoken` call
- Clearing `sessionId` if exists after `sessionclose` call
- Returns `sessionId` as part of `liveChatContext` if exists
- Reassigning `sessionId` on methods which using `liveChatContext`
- `ChatSDK.getConversationDetails()`
- `ChatSDK.getLiveChatTranscript()`
- `ChatSDK.emailLiveChatTranscript()`
> `sessionId` Lifecycle Handling

- CHANGELOG.md
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
For GetPostChatSurveyContext , when liveworkitem details is returninig null, it wont continue with the flow.
- not showing survey
> adding handle of missing conversation

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- src/OmnichannelChatSDK.ts
Will not break current flow, as survey provider (acting as a fcb) is checked first in the backend
> Adding survey provider to getinvitelink call for MCS survey

- CHANGELOG.md
- __tests__/utils/utilities.spec.ts
- docs/pull_request_template.md
- playwright/integrations/utilities.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/ChatSDKConfig.ts
- src/core/OmnichannelConfig.ts
- src/utils/utilities.ts
Gap identified as part of engineering enhancement.
- Expose a new config attribute, when the attribute is present then that value will be used, when the value is not present then a new UUID will be generated
- Expose a new config attribute, when the attribute is present then that value will be used, when the value is not present then a new UUID will be generated
- Telemetry shares same runtimeId value for telemetry
_Include what tests cases were considered, any evidence of testing for future references, to identify any …
> adding sync mechanism

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/utils/setOcUserAgent.spec.ts
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
- src/core/ChatSDKConfig.ts
- src/external/OCSDK/IOCSDKLogData.ts
- src/telemetry/AriaTelemetry.ts
- src/utils/loggers.ts
- src/utils/setOcUserAgent.ts
Task: 3985297
- Sending default OC User Agent HTTP Request Headers for better analytics
- Add ability to send additional OC User Agent HTTP Request Headers
- OC User Agent should be sent as part of every HTTP calls
- Validated the scenario 
- Verified scenario with telemetry logs
> Add Ability to Send OC User Agent

- CHANGELOG.md
- __tests__/telemetry/retrieveCollectorUri.spec.ts
- src/telemetry/GCCDomainPatterns.ts
- src/telemetry/retrieveCollectorUri.ts
- src/utils/CoreServicesUtils.ts
- Add `crm9` as part of CoreServicesGeoNamesMapping
- Update `retrieveCollectorUri` to return GCCCollectorUri accordingly
> Core services GCC

- CHANGELOG.md
- __tests__/utils/CoreServicesUtils.spec.ts
- src/utils/CoreServicesUtils.ts
Updated unit test because jest consider null as defined. Because of the unit test where not executing properly for regex exec function which return null
Updated regex and unit test
> crmtest unq url and unit test update

- CHANGELOG.md
- package-lock.json
- package.json
4255474
The chat wi.dget remains in a loading state continuously
This is due to sometimes getchattoken endpoint is unresponsive, causing the widget to hand due to a improper way to send reject the promisse in ocsdk
patch was already applied in OCSDK
> bump ocsdk

- playwright/integrations/authenticated-chat-with-attachments.spec.ts
- playwright/integrations/authenticated-chat-with-masking.spec.ts
- playwright/integrations/authenticated-chat-with-persistent-chat.spec.ts
- playwright/integrations/authenticated-chat-with-prechat.spec.ts
- playwright/integrations/authenticated-chat-with-reconnect.spec.ts
- playwright/integrations/authenticated-chat-with-transcripts.spec.ts
- playwright/integrations/authenticated-chat-with-typing.spec.ts
- playwright/integrations/authenticated-chat.spec.ts
- playwright/integrations/unauthenticated-chat-with-attachments.spec.ts
- playwright/integrations/unauthenticated-chat-with-masking.spec.ts
- playwright/integrations/unauthenticated-chat-with-prechat.spec.ts
- playwright/integrations/unauthenticated-chat-with-reconnect.spec.ts
- playwright/integrations/unauthenticated-chat-with-transcripts.spec.ts
- playwright/integrations/unauthenticated-chat-with-typing.spec.ts
- playwright/integrations/unauthenticated-chat.spec.ts
- playwright/test.config.sample.yml
- playwright/utils/fetchTestSettings.ts
Task: #4329297
- Fix Playwright Integrations Tests
- Tests were running "too fast"
- Calling `ChatSDK.startChat()` then `ChatSDK.endChat()` too quickly would cause failures on `sessionclose` given that the `LiveWorkItem` may not be fully created and available to be retrieved from the DB
- Added a configurable setting `chatDuration` to mimic the scenario of a normal person chatting would resolve the issue
- Integration tests should be more reliable 
- Ran the integration tests with 100% success rate
> Fix Integration Tests with Chats Running Too Fast

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
- src/config/settings.ts
This is to make sure that omnichannel-chat-sdk callingbundle dependency is tied to specific version so that clients do not break when there is an update to callingBundle.
LCW pipeline added versioned folder for upcoming callingBundle.
> adding new versioning logic for calling bundle

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
Bug #4292896
- Add `requestId` to  `OCClient.getReconnectableChats()` parameters to update API with `requestId` instead of `orgId`
> Fix Reconnectable Chats API

- playwright/integrations/authenticated-chat-with-persistent-chat.spec.ts
- playwright/integrations/authenticated-chat-with-reconnect.spec.ts
This PR includes the fixes for the following chat scenarios,
Modified API URL for reconnectable chats. Replaced org id with request id.
- ChatSDK.startChat() should have a reconnect id if there's an existing chat session
- ChatSDK.getChatReconnectContext() should not return a reconnect id if there's no existing chat session
- ChatSDK.getChatReconnectContext() should return a reconnect id if there's an existing chat session
- ChatSDK.startChat() should not have any reconnect id if there's no existing chat session
> Fix Integration Tests- Modify Reconnectable Chats API URL

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.node.spec.ts
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDK.web.spec.ts
- __tests__/OmnichannelChatSDKParallel.node.spec.ts
- __tests__/OmnichannelChatSDKParallel.spec.ts
- __tests__/OmnichannelChatSDKParallel.web.spec.ts
- __tests__/api/createVoiceVideoCalling.web.spec.ts
- __tests__/core/messaging/ACSClient.spec.ts
- __tests__/external/ACSAdapter/AMSFileManager.spec.ts
- __tests__/external/ACSAdapter/AMSFileScanner.spec.ts
- __tests__/external/ACSAdapter/createFormatEgressTagsMiddleware.spec.ts
- __tests__/telemetry/AriaTelemetry.spec.ts
- __tests__/telemetry/ScenarioMarker.spec.ts
- __tests__/utils/CoreServicesUtils.spec.ts
- __tests__/utils/InternalUtils.spec.ts
- __tests__/utils/WebUtils.web.spec.ts
- __tests__/utils/createOmnichannelMessage.spec.ts
- __tests__/utils/locale.spec.ts
- __tests__/utils/loggers.spec.ts
- __tests__/utils/setOcUserAgent.spec.ts
- __tests__/utils/sleep.spec.ts
- __tests__/validators/SDKConfigValidators.spec.ts
- package-lock.json
- package.json
- playwright/integrations/unauthenticated-chat.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/EndChatOptionalParams.ts
- src/telemetry/TelemetryEvent.ts
For sessions that were disconnected , or ended by agent, when calling endchat is forcing an exception since the conversation is already closed.
Adding optional parameters to allow the caller to identify when a call to end chat is for an already closed chat, this will avoid to call close chat endpoint.
- extra lines
- trail spaces
- unused variables
- rename let to const
- whitelist for empty arrow functions
- whitelist for any 
- whitelist unused declared variables inside callbacks
- fix tabs and spaces
_Include what …
> End Chat Optional Parameter

- CHANGELOG.md
- README.md
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDKParallel.spec.ts
- playwright/README.md
- playwright/integrations/unauthenticated-chat-with-prechat.spec.ts
- playwright/integrations/unauthenticated-chat.spec.ts
- src/OmnichannelChatSDK.ts
- src/types/config.d.ts
- src/types/response.d.ts
Missing types definition in public exposed API methods for the SDK, using `any` by default, even for those that have an explicit type to be returned.
- Adding types as response object for API methods that return a type defined, but for some reason the response is set as `any`
- Defining new types for those methods that doesn't have a type, or are using `any` because the type to return varies on the flow.
- New types are oriented to be frictionless to avoid breaking changes
- API methods exposed should no return `any` …
> Adding missing types

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/messaging/ACSClient.ts
- src/utils/createOmnichannelMessage.ts
Under certain scenarios, messages coming from PVA are not passed to the callback function , due to an exception while iterating messages.
Ensure an exception during iteration of messages doesnt disrupt the iteration.
additional it was removed code related to V1.
- Messages are always presents and callback is executed when subscribed to onNewMessage
- V1 code is removed and tests updated
***Please …
> Fix for OnNewMessage Listener

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
- src/core/messaging/ACSClient.ts
- src/core/messaging/ACSClientGetMessagesOptionParams.ts
> Fix get message dup calls

- CHANGELOG.md
- src/core/messaging/ACSClient.ts
Complains over possible scenarios due to latencies with websocket creation, causing the first message from copilot to do not be ready to be presented after 30 seconds, due to our internal clock for fetching.
Adding a mechanism for fetching from 1sec to max 10 secs while waiting for websocket to be ready.
This mechanism is only for users not using webchat adapter.
***Please provide justification …
> Adding mechanism for better fetching of messages while waiting for websocket

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDKParallel.spec.ts
- playwright/public/index.html
- playwright/public/scripts/sdk.js
- src/OmnichannelChatSDK.ts
- src/core/messaging/ACSClient.ts
In some scenarios, customer states first message from copilot is "lost", it seems this is due to an off-sync when websocket is initializing and pooling stops.
- Enable Pooling to continue for 10 secs after websocket has initialized, as backup , to prevent messages in transit being lost
- When endchat is called, ensure pooling is stop as well
***Please provide justification if any of the …
> Implement continue pooling

- CHANGELOG.md
- src/telemetry/AriaTelemetry.ts
- tsconfig.json
- Adapter version is not reflected correctly in telemetry
> Fix Telemetry Adapter Version

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
Checking if conversation ended when onAgentEndSession call back is fired, 
> checking for conversationState when participants is removed

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
BUG 4729209
getLiveChatTranscript failed if download transcript happens after endChat for persistent chat
added additional check for persistent chat with livechatcontext if download transcript happens after endChat 
> updated getLiveChatTranscript for persistent chat livechatcontext

- CHANGELOG.md
- __tests__/core/messaging/ACSClient.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/ChatSDKError.ts
- src/core/messaging/ACSClient.ts
[BUG 4787637](https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/4787637)
Ensure exception details contains propagated data
Add exception details for sendMessage calls for telemetry with propagated data.
Verified locally and able to see exception details in telemetry for sendMessagesFailed event of ocsdk.
> Added exception details for sendMessage telemetry

- CHANGELOG.md
- __tests__/utils/createOmnichannelMessage.spec.ts
- src/core/messaging/OmnichannelMessage.ts
- src/utils/createOmnichannelMessage.ts
- Expose `OriginalMessageId` on `ChatSDK.onNewMessage()` to handle message ordering
> Update Message Properties

- CHANGELOG.md
- README.md
- __tests__/core/messaging/ACSClient.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/messaging/ACSClient.ts
- Update `ChatSDK.sendMessage()` to return `OmnichannelMessage`
> Update Send Message

- CHANGELOG.md
- README.md
- __tests__/OmnichannelChatSDK.node.spec.ts
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDK.web.spec.ts
- __tests__/OmnichannelChatSDKParallel.node.spec.ts
- __tests__/OmnichannelChatSDKParallel.spec.ts
- __tests__/OmnichannelChatSDKParallel.web.spec.ts
- package.json
- src/OmnichannelChatSDK.ts
- src/core/ChatSDKError.ts
- src/core/InitializeOptionalParams.ts
- src/utils/exceptionThrowers.ts
- Detected a double load of AMS when debug is declared.
- Detected scenario where startChat is finishing before AMS is loaded, causing disruption when trying to load files , or during reload , files already attached may not be present.
 
- Patch to prevent double load
- Patch to prevent start chat to finish before AMS is loaded
- Load AMS only when config is enabled for agent or customer, otherwise do not load it.
__SDK needs to ensure AMS is loaded before session starts, the delay in the load needs to be investigated in AMS client__
_Define what are the conditions to consider the PR has achieved the …
> Load AMS based on config definition

- README.md
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
- src/core/OmnichannelConfig.ts
Depends on https://github.com/microsoft/omnichannel-sdk/pull/135
cpsBotId in UUID format, when present will use v4 for GetchatToken. (Limited to enabled orgs) establishing the connection with Copilot Bot specified.
- if bot id is present and valid, SDK will use `V4` for `GetchatToken` establishing the connection with the dessired Copilot Bot.
- if bot Id is not present, flow will continue using `V2` for `GetchatToken`
- if bot Id is not in valid format, expect a `400 HTTP Response Error Code`
- if bot Id is not enabled for the workstream, expect `403 HTTP Response Error Code`
```ts
import …
```
> Extend getchat token : pass Ms-Oc-Bot-Application-Id

- playwright/integrations/unauthenticated-chat.spec.ts
- playwright/utils/OmnichannelEndpoints.ts
This PR includes the following scenario,
1. Verify `useCreateConversation.disable: false` triggers Create Conversation flow
> Integration Test- Verify 'useCreateConversation.disable: false' triggers Create Conversation flow

- CHANGELOG.md
- __tests__/utils/utilities.spec.ts
- src/core/messaging/OmnichannelMessage.ts
- src/utils/createOmnichannelMessage.ts
- src/utils/utilities.ts
Added role attribute for bot message in onNewMessageCallback
Added role attribute for bot message to identify message received from bot.
verified locally
> Added 'role' attribute for bot messages

- playwright/integrations/authenticated-chat-with-persistent-chat.spec.ts
- playwright/integrations/authenticated-chat-with-prechat.spec.ts
- playwright/integrations/authenticated-chat-with-reconnect.spec.ts
- playwright/integrations/authenticated-chat.spec.ts
- playwright/integrations/unauthenticated-chat-with-prechat.spec.ts
- playwright/integrations/unauthenticated-chat-with-reconnect.spec.ts
- playwright/integrations/unauthenticated-chat.spec.ts
Modified the below scenarios,
1. ChatSDK.startChat() with preChatResponse should be part of session init payload
2. ChatSDK.startChat() should have a reconnect id if there's an existing chat session
3. ChatSDK.startChat() with liveChatContext should not perform session init & validate the live work item details & validate auth map record
4. ChatSDK.startChat() should fetch the chat token & perform session init
5. ChatSDK.startChat() with a valid reconnect id should reconnect to previous chat 
6. ChatSDK.startChat() with customContext should be part of session init payload 
7. ChatSDK.startChat() with sendDefaultInitContext should send default init contexts
8. ChatSDK.getChatReconnectContext() with invalid reconnect id & redirect URL should only return a redirect URL
9. ChatSDK.startChat() …
> Fix Integration Tests- ChatSDK.initialize() with ChatSDK Configuration "useCreateConversation" disabled

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
EndChat exceptionDetails missing the error message from the oc-sdk sessionclose api call
Also need to split request in promiseAll because eve if sessionInit fails ,other promises where continuing in background causing ACS connection created without a successfull sesionInit
> added error message to endchatfailed

- CHANGELOG.md
- src/utils/createOmnichannelMessage.ts
To support clients who are depending on originalMessageId for rendering , we need to map ID to original message id property
> backward compatibility for original message id

- CHANGELOG.md
- src/core/messaging/OmnichannelMessage.ts
- src/utils/createOmnichannelMessage.ts
This change introduces a mechanism for customers to send event information from their mobile application to a bot via ACS chat. These events can represent in-app actions that the bot may need to respond to in real time.
For example, imagine a customer interacting with a support bot inside a shopping app. If the customer adds a product to their cart that doesn’t align with their stated preferences, the bot can detect this event, provide a helpful suggestion, and recommend a more suitable product—all based on the custom event data received from the app.
To enable this behavior, we’re introducing support for invisible (non-rendered) messages in the ACS chat thread that contain custom event metadata. These messages include three optional fields in the metadata:
- `customEvent`: A flag to …
> Support custom event metadata propagation to mobile SDKs (Android/iOS)

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/SurveyProvider.ts
**Id of the task, bug, story or other reference**
*Include a description of the problem to be solved*
When calling `OCClient.getSurveyInviteLink`, the `FormId` property in the request body is required if `SurveyProvider` is `600990000` (Customer Voice). `ConversationId` is required regardless of the value of `SurveyProvider`. Currently, we don't validate either of these properties when `OCClient.getSurveyInviteLink` is called in the `getPostChatSurveyContext` method.
In `getPostChatSurveyContext`, reject and skip the request to `OCClient.getSurveyInviteLink` if either:
- `msfp_sourcesurveyidentifier` is empty and `msdyn_surveyprovider` is `600990000`
- Response payload from `OCClient.getLWIDetails` contains no valid conversation ID.
_Define what are the conditions to consider the PR has …
> Validate getSurveyInviteLink request payload.

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.node.spec.ts
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDK.web.spec.ts
- __tests__/OmnichannelChatSDKParallel.node.spec.ts
- __tests__/OmnichannelChatSDKParallel.spec.ts
- __tests__/OmnichannelChatSDKParallel.web.spec.ts
- package-lock.json
- package.json
- playwright/public/index.html
- playwright/public/scripts/oauth-sdk.js
- src/OmnichannelChatSDK.ts
- src/core/ChatSDKError.ts
- src/core/GetPersistentChatHistoryOptionalParams.ts
- src/index.ts
- src/telemetry/TelemetryEvent.ts
- src/types/response.d.ts
- src/utils/exceptionThrowers.ts
This pull request introduces a new method to the SDK for retrieving persistent chat history for authenticated chats, along with comprehensive tests to ensure its correct behavior across platforms and initialization modes. It also updates the SDK dependency and improves performance for survey invite link requests.
* Added `ChatSDK.getPersistentChatHistory()` method to enable retrieval of persistent chat history for authenticated users. This includes robust error handling for various failure scenarios, such as uninitialized SDK, disabled persistent chat, missing authenticated token, and backend failures. [[1]](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR7-R16) [[2]](diffhunk://#diff-3f04a8141d95bb78b5936d039c2177f55e803e83f8a78d897afb274ad09a128aR3188-R3 …
> Sdk persistent history chat
