microsoft/omnichannel-chat-sdk

- __tests__/OmnichannelChatSDK.node.spec.ts
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDK.web.spec.ts
- __tests__/utils/libraries.spec.ts
- __tests__/utils/platform.node.spec.ts
- __tests__/utils/platform.web.spec.ts
- __tests__/validators/SDKConfigValidators.spec.ts
- src/OmnichannelChatSDK.ts
- src/validators/SDKConfigValidators.ts
> Add tests to increase code coverage

- src/OmnichannelChatSDK.ts
> Add flag for Persistent Chat 

- src/OmnichannelChatSDK.ts
- src/core/IChatSDKConfig.ts
- src/validators/SDKConfigValidators.ts
- Create the interface for the Persistent Chat FCB
- Set the default values for the Persistent Chat FCB
> Persistent Chat FCB

- __tests__/OmnichannelChatSDK.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/ConversationMode.ts
-Using Conversation Mode to determine if a chat is a live chat or persistent chat.
> Check Conversation Mode

- src/OmnichannelChatSDK.ts
Added logic to check if a chat has a reconnect id
> Fetch Reconnectable Chats 

- src/OmnichannelChatSDK.ts
- src/telemetry/TelemetryEvent.ts
This contains logic to update chat token
> Add logic for updating Chat Token

- README.md
New documentation for Persistent Chat and Chat Reconnect
> These are documentation for Persistent Chat and Chat Reconnect

- src/OmnichannelChatSDK.ts
- src/telemetry/AriaTelemetry.ts
- src/telemetry/ScenarioMarker.ts
- src/utils/loggers.ts
> Add runtime id field for telemetry

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- src/OmnichannelChatSDK.ts
> Fix close chat reconnect session

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/utils/WebUtils.web.spec.ts
- src/OmnichannelChatSDK.ts
- src/utils/WebUtils.ts
> Fix heartbeat not sending

- docs/DEVELOPMENT_GUIDE.md
> Development Guide using Web-Chat

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- src/OmnichannelChatSDK.ts
- Add API to validate auth chat record when starting chat with `liveChatContext`
> Auth chat validation

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
- Enable to ability to create multiple iframes for AMSClient
Addressing #145
> Enable AMSClient multi-client support

- README.md
- Update installation steps through running ChatSDK on React Native `v0.70.5`
> Update React Native Installation Steps

- CHANGELOG.md
- src/utils/chatAdapterCreators.ts
- Wrong optional param was used for ingress middleware
> Fix egressMiddleware optional param being used in ingress middleware

- CHANGELOG.md
- README.md
- __tests__/OmnichannelChatSDK.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/GetAgantAvailabilityOptionalParams.ts
- src/core/GetAgentAvailabilityOptionalParams.ts
- src/telemetry/TelemetryEvent.ts
Feature parity with GetAgentAvailability in LCW V1
> Implement GetAgentAvailability Method

- __tests__/OmnichannelChatSDK.node.spec.ts
- __tests__/OmnichannelChatSDK.web.spec.ts
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
- src/core/StartChatOptionalParams.ts
- src/telemetry/TelemetryEvent.ts
- src/utils/location.ts
> Adding GetGeolocation call in startChat if enabled

- playwright/README.md
- playwright/integrations/authenticated-chat.spec.ts
- playwright/test.config.sample.yml
- playwright/utils/OmnichannelEndpoints.ts
- playwright/utils/fetchAuthUrl.ts
- Add ability to run authenticated chat tests
> Integration tests

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.node.spec.ts
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDK.web.spec.ts
- src/OmnichannelChatSDK.ts
- Update `ChatSDK.liveChatVersion` default value to be `LiveChatVersionV2`
> Set Default Live Chat Version to V2

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
[Bug 3375745](https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/3375745): [V2] [reliability] multiple records of failures for undefined elements trying to call toString
> Add null check for startChat exception check

- CHANGELOG.md
- src/core/messaging/ACSClient.ts
- Removing redundant API call since it's not being used and would increase time to initialize ChatSDK
> Retrieve Participants Optimization

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/telemetry/retrieveCollectorUri.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/ChatSDKConfig.ts
- src/telemetry/EUDomainNames.ts
- Updated EU domains names to ensure telemetry is flowing to the right location
- Unit tests to validate every EU domain is returning the proper URI
- Verified in the network traces that the telemetry API is performing the request at the right location
> Update EU domain names

- src/api/createVoiceVideoCalling.ts
- src/utils/loggers.ts
We have added the log scenario operation in Calling SDK logger. Adding this function here. We have already updated this in LCW
> Add callingsdk interface method to logger.ts

- src/OmnichannelChatSDK.ts
Added method to check if voice and video calling option is enabled.
> 3851573: [v2] LCW closeChat methods throws exception

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/utils/CoreServicesUtils.spec.ts
- __tests__/utils/InternalUtils.spec.ts
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
- src/config/ocSDKConfiguration.ts
- src/core/AxiosErrorCodes.ts
- src/core/ChatSDKConfig.ts
- src/utils/CoreServicesUtils.ts
- src/utils/internalUtils.ts
- src/utils/loggerUtils.ts
- Add ability to dynamically use `CoreServices` orgUrl at runtime
- Add fallback mechanism if `CoreServices` orgUrl fails with DNS URL Resolve error
User Story: 3916869
> Core services OrgUrl Conversion

- CHANGELOG.md
- package-lock.json
- package.json
> Bump v1.8.3

- CHANGELOG.md
- package-lock.json
- package.json
> Uptake @microsoft/ocsdk

- CHANGELOG.md
- package-lock.json
- package.json
> Bump v1.9.2 0

- README.md
Fix miscellaneous typos in README
> Fix miscellaneous typos in README

- CHANGELOG.md
- package-lock.json
- package.json
- playwright/integrations/unauthenticated-chat.spec.ts
- src/OmnichannelChatSDK.ts
- src/utils/setOcUserAgent.ts
4300135
axios 1.7.2 allows SSRF via unexpected behavior where requests for path relative URLs get processed as protocol relative URLs.
Upgrade axios from 1.6.1 to 1.7.4 to fix the vulnerability.
components affected already include new patch for axios
╰─ﬀ npm ls axios
@microsoft/omnichannel-chat-sdk@1.9.4-0 C:\src\forks\omnichannel-chat-sdk
+-- @microsoft/ocsdk@0.4.5
| `-- axios@1.7.4
`-- @microsoft/omnichannel-ic3core@0.1.4
`-- axios@1.7.4 deduped
manual validation
_Include what tests cases were considered, any …
> Update axios dependencies

- CHANGELOG.md
- package-lock.json
- package.json
> Bump v1.9.4.0

- CHANGELOG.md
- package-lock.json
- package.json
> bump 1.9.6-0

- CHANGELOG.md
- package-lock.json
- package.json
> Bump v1.9.6

- CHANGELOG.md
- package-lock.json
- package.json
> bump new version v-1.9.8-0

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.node.spec.ts
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDK.web.spec.ts
- __tests__/OmnichannelChatSDKParallel.node.spec.ts
- __tests__/OmnichannelChatSDKParallel.spec.ts
- __tests__/OmnichannelChatSDKParallel.web.spec.ts
- __tests__/core/messaging/ACSClient.spec.ts
- __tests__/utils/chatAdapterCreators.web.spec.ts
- __tests__/utils/exceptionThrowers.spec.ts
- package-lock.json
- package.json
- scripts/copy_files.js
Updating libraries and unit tests fix, including adding a node script to copy files, since currently we use a `cp` command which fails if not being executed in a batch console.
> update of libs, plus unit tests fix

- CHANGELOG.md
- package-lock.json
- package.json
Updating ocsdk version to 0.5.7
> udpate-ocsdk

- CHANGELOG.md
- package-lock.json
- package.json
> Bump 1.9.10

- CHANGELOG.md
- package-lock.json
- package.json
> uptake OCSDK 0.5.8 (getchatconfig timeout : 120s)

- CHANGELOG.md
- package-lock.json
- package.json
> Bump v1.10.1

- package.json
- src/core/messaging/ChatAdapterOptionalParams.ts
- src/external/ACSAdapter/AdapterErrorEvent.ts
- src/external/ACSAdapter/IErrorEventSubscriber.ts
- src/utils/chatAdapterCreators.ts
Task 4461653
- Expose adapter's `errorEventSubscriber` parameter to subscribe to adapter error events
> Chat Adapter Error Event Subscriber

- CHANGELOG.md
- package-lock.json
- package.json
leap forward in core libraries for omnichannel chat sdk.
- uptake [azure/communication-chat@1.5.0](https://www.npmjs.com/package/@azure/communication-chat/v/1.5.0)
- uptake [azure/communication-common@2.3.1](https://www.npmjs.com/package/@azure/communication-common/v/2.3.1)
- uptake [acs_webchat-chat-adapter@0.0.35-beta.30](https://www.npmjs.com/package/acs_webchat-chat-adapter/v/0.0.35-beta.30)
-
_Include what tests cases were considered, any evidence of testing for future references, to identify any corner cases, …
> Update of versions for core libraries

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
- src/core/OmnichannelErrorCodes.ts
> console log for cx developers when widget id is no longer found in the system

- CHANGELOG.md
- package-lock.json
- package.json
> Bump v1.10.2

- CHANGELOG.md
- package-lock.json
- package.json
> Bump 1 10 3

- CHANGELOG.md
- src/index.ts
Types missed to be added as part of the export.
> exporting types

- CHANGELOG.md
- package-lock.json
- package.json
> Bump v1.0.4

- CHANGELOG.md
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
- Some public API's doenst have implemented the Failed Event
- Missing validations to prevent exposed API;s to be called before SDK initialization
- Adding missing functionality and telemetry
> Telemetry update & Initialization Validations

- CHANGELOG.md
- package-lock.json
- package.json
> Bump 1.10.6 0

- README.md
Updated readme file to include a new section for handling chat disconnect on mobile platforms.
> udpated doc

- CHANGELOG.md
- package-lock.json
- package.json
> Bump version 1.7-0

- CHANGELOG.md
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
- src/core/StartChatOptionalParams.ts
Adding new properties to sessionInit optional params for push notification in native devices
> adding push notification props

- CHANGELOG.md
- package-lock.json
- package.json
> New Release 1.10.9 and prepatch  v1.10.10-0

- CHANGELOG.md
- package-lock.json
- package.json
> Bumpv 1.10.12 0

- CHANGELOG.md
- package.json
> Bump v1.10.13

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/core/messaging/ACSClient.spec.ts
- src/OmnichannelChatSDK.ts
- src/commands/startPolling.ts
- src/commands/stopPolling.ts
- src/core/messaging/ACSClient.ts
- src/core/messaging/ACSRegisterOnNewMessageOptionalParams.ts
- src/core/messaging/OnNewMessageOptionalParams.ts
- src/telemetry/TelemetryEvent.ts
> Polling Improvements

- CHANGELOG.md
- package-lock.json
- package.json
> Bumpv1.10.15

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDKParallel.spec.ts
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
> fix and uptakes

- CHANGELOG.md
- package-lock.json
- package.json
> Bump v1.16 0

- CHANGELOG.md
- package-lock.json
- package.json
> Bump v1.10.18-0

- CHANGELOG.md
- package-lock.json
- package.json
> Bump v1.10.19 0

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.node.spec.ts
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDK.web.spec.ts
- __tests__/OmnichannelChatSDKParallel.node.spec.ts
- __tests__/OmnichannelChatSDKParallel.spec.ts
- __tests__/OmnichannelChatSDKParallel.web.spec.ts
- __tests__/core/messaging/ACSClient.spec.ts
- src/OmnichannelChatSDK.ts
- src/core/messaging/ACSClient.ts
- src/validators/SDKConfigValidators.ts
Propagating underlying error data to the caller of the API
> udpated error to include additional details

- CHANGELOG.md
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
- src/utils/exceptionThrowers.ts
This pull request includes several updates to improve error handling, enhance robustness, and update dependencies in the `OmnichannelChatSDK`. The most important changes focus on refining exception handling, ensuring fallback values for optional parameters, and updating a dependency version.
* Enhanced the `throwChatSDKError` function in `src/utils/exceptionThrowers.ts` to include detailed error information when the error object contains a `response` property. This ensures better debugging and logging capabilities by serializing relevant fields like `status`, `headers`, and `data`.
* Updated the `closeChat` method in `src/OmnichannelChatSDK.ts` to ensure that the `disconnect` logic is executed in a `finally` block, guaranteeing cleanup …
> Uptake oc sdk

- README.md
- src/OmnichannelChatSDK.ts
- src/core/DebugOptionalParams.ts
- src/utils/loggerUtils.ts
When using set debug, it enable debug telemetry for SDK, OCSDK, ACS Client , ACS Adapter and Attachment components, 
which as shown , is extremely noisy, practically it has not benefit for developers
``` javascript
await chatSDK.setDebugDetailed({
flagSDK: true,
flagACS: false,
flagAttachment: false,
});
```
> new debug function to operate by components

- docs/DEVELOPMENT_GUIDE.md
- Update documentation with correct property to retrieve `originalMessageId`
reference : https://github.com/microsoft/omnichannel-chat-sdk/issues/451
> Update Documentation 

- CHANGELOG.md
- __tests__/OmnichannelChatSDK.spec.ts
- __tests__/OmnichannelChatSDKParallel.spec.ts
- package-lock.json
- package.json
- src/OmnichannelChatSDK.ts
This pull request introduces several updates to the `OmnichannelChatSDK` to enhance functionality and error handling, along with a minor dependency update in the `package.json` file. The most notable changes include adding a `requestId` initialization where necessary, improving error handling for missing `chatId`, and updating the `@microsoft/ocsdk` dependency.
> Uptake new oc sdk and changes to requestId

- README.md
> Readme update for React Native >= 0.71

- CHANGELOG.md
- package-lock.json
- package.json
> Bump 1.11.4 0

- CHANGELOG.md
- package-lock.json
- package.json
> Bump 1.11.5-0

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
> udpate fix to yml

- CHANGELOG.md
- package.json
> Bump 1.11.6-0

- .github/prompts/release.prompt.md
> added a new release prompt

- CHANGELOG.md
- src/OmnichannelChatSDK.ts
flow is still validating on v1 version which is not longer in use, removing the path in case may be causing conflicts with native implementations 
> remove V1 logic for onAgentEndSession
